# -*- coding: utf-8 -*-
"""day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWbOiaZG-Nx-euxI3Psjxa3WI2lfX0bW
"""

forces=np.array([10,20,30])
lenght=np.array([2,4,6])
moments=forces*lenght
print("Moments:",moments)



# Demonstrate another numpy operation
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2
print("Sum of arrays:", sum_array)

# Calculate a percentage
part = 75
whole = 100
percentage = (part / whole) * 100
print(f"The percentage is: {percentage}%")



import numpy as np

# Define forces and corresponding lengths
forces = np.array([10, 20, 30]) # in Newtons
lengths = np.array([2, 4, 6]) # in meters

# Calculate moments (Force * Length)
moments = forces * lengths

# Print the results

print(f"Moments:{moments} nm" )

rows=

rows=10
for j in range(1,rows+1):
  print(" "*(rows-j)+"* "*j)

